/**
 * UNIT ADALAH SISTEM UNTUK PENGEMBALIAN DATA DARI FUNCTION LAIN KE FUNC MAIN()
 * CONTOH DISINI KITA MEMBUAT SEBUAH FUNCTION KOSONG.
 * LALU KITA MASUKKAN NAMA FUN NYA KE FUN MAIN(),DAN KITA TAHAN AJA KURSOR NYA DI FUN YANG DI MASUKKAN TADI.
 * OTOMATIS ADA BACAAN UNIT.YANG DIMANA UNIT ADALAH SISTEM PENGEMBALIAN DATA.
 * SEBENARNYA INI TIDAK WAJIB,TAPI INI PERLU DIPELAJARI UNTUK FUNDAMENTAL LANGUANGE PEMGORAMAN KOTLIN.
 * SEPERTI CONTOH KODE BERIKUT :
 */

fun hello(){
    println("Hello World")
}

/**
 * CARA PENGGUNAAN UNIT YANG SEBENARNYA,
 * KITA AMBIL CONTOHNYA SEPERTI DI ATAS :
 * FUN HELLO(){
 * println("Hello World")
 * } .
 * UNTUK YANG UNIT :
 * FUN HELLO():UNIT{
 * println("Hello World")
 * } <- SEPERTI ITU CONTOH UNIT NYA,CUMAN DIKARENAKAN MENGGUNAKAN UNIT INI TIDAK WAJIB
 * JADI TIDAK APA-APA,KECUALI KITA MEMEASUKKAN LANGSUNG TIPE DATANYA,BARU UNIT ITU DI GANTI DENGAN
 * TIPE DATA YANG SESUAI DENGAN KITA MASUKKAN.
 */

fun main(){
    // Disini kita masukkan fun yang di atas.
    hello()
    /**
     * LALU TAHAN KURSOR KE FUN HELLO() TERSEBUT DAN OTOMATIS ADA BACAAN ROOT<>UNIT
     */
}